### ISSUE TITLE
Burdens - Does not handle the case where a weapon (or all weapons) are stripped from a player

### ISSUE THREAD

**Issue by Malivil** [TheStig294/100-more-randomats-pack-1#3]
Couple options to get around it:

1. Override plymeta:StripWeapon and adjust speed. You would have to make sure to remove the override when the event ends though
2. Instead of hooking WeaponEquip/PlayerDroppedWeapon you can use Think or a timer and check how many weapons a player has and set the speed that way

**Comment by TheStig294** [comment]
Sorry, was already working on this and made other changes: c5927bf0c1e3ca502dc7c34fc57998b16655aab0

**Comment by Malivil** [comment]
No worries, figured I would take a cut at it while I was doing TTT stuff =)
